// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AqhWQjr-RUI0t6WkPAFZkOhdbqYD3C0',
    appId: '1:861704699683:web:3730438ff93e52902bd696',
    messagingSenderId: '861704699683',
    projectId: 'shuttle-spirit',
    authDomain: 'shuttle-spirit.firebaseapp.com',
    storageBucket: 'shuttle-spirit.firebasestorage.app',
    measurementId: 'G-ZYNMBDJKP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGa_--fx6x5LryYOMUc-JzO6gbNFZEl1Y',
    appId: '1:861704699683:android:0f09ce09a3f132132bd696',
    messagingSenderId: '861704699683',
    projectId: 'shuttle-spirit',
    storageBucket: 'shuttle-spirit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHAJGWOFyNr2KqdZhJW-MrUApxp0YBlk',
    appId: '1:861704699683:ios:78605a327cc5ae3a2bd696',
    messagingSenderId: '861704699683',
    projectId: 'shuttle-spirit',
    storageBucket: 'shuttle-spirit.firebasestorage.app',
    iosBundleId: 'com.example.shuttleSpirites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHAJGWOFyNr2KqdZhJW-MrUApxp0YBlk',
    appId: '1:861704699683:ios:78605a327cc5ae3a2bd696',
    messagingSenderId: '861704699683',
    projectId: 'shuttle-spirit',
    storageBucket: 'shuttle-spirit.firebasestorage.app',
    iosBundleId: 'com.example.shuttleSpirites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4AqhWQjr-RUI0t6WkPAFZkOhdbqYD3C0',
    appId: '1:861704699683:web:e24d64c3231b83a02bd696',
    messagingSenderId: '861704699683',
    projectId: 'shuttle-spirit',
    authDomain: 'shuttle-spirit.firebaseapp.com',
    storageBucket: 'shuttle-spirit.firebasestorage.app',
    measurementId: 'G-R8GE61Y5NV',
  );
}
