// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoPQJSLVJ3Psx7xwwYL4dDBgD_f8r9FMw',
    appId: '1:249747045953:web:c8277e600e8967eda010c0',
    messagingSenderId: '249747045953',
    projectId: 'shuttle-spirit-23974',
    authDomain: 'shuttle-spirit-23974.firebaseapp.com',
    storageBucket: 'shuttle-spirit-23974.firebasestorage.app',
    measurementId: 'G-58TNSVJC70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ID0alZN8dwRqrDk6ep3T5qQEaB6oi5Q',
    appId: '1:249747045953:android:c05b73f2ef4367f1a010c0',
    messagingSenderId: '249747045953',
    projectId: 'shuttle-spirit-23974',
    storageBucket: 'shuttle-spirit-23974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeuP6hfFRkrakR4CQjzLaTwb17-txTv2s',
    appId: '1:249747045953:ios:2255a73b89ba2ed7a010c0',
    messagingSenderId: '249747045953',
    projectId: 'shuttle-spirit-23974',
    storageBucket: 'shuttle-spirit-23974.firebasestorage.app',
    iosBundleId: 'com.example.shuttleSpirites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeuP6hfFRkrakR4CQjzLaTwb17-txTv2s',
    appId: '1:249747045953:ios:2255a73b89ba2ed7a010c0',
    messagingSenderId: '249747045953',
    projectId: 'shuttle-spirit-23974',
    storageBucket: 'shuttle-spirit-23974.firebasestorage.app',
    iosBundleId: 'com.example.shuttleSpirites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoPQJSLVJ3Psx7xwwYL4dDBgD_f8r9FMw',
    appId: '1:249747045953:web:9ce3300c4f9aff37a010c0',
    messagingSenderId: '249747045953',
    projectId: 'shuttle-spirit-23974',
    authDomain: 'shuttle-spirit-23974.firebaseapp.com',
    storageBucket: 'shuttle-spirit-23974.firebasestorage.app',
    measurementId: 'G-C72Q1JKR75',
  );
}
